### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by viniciolindo** [TsubokuLab/ofxBezierWarpManager#1]
i'd like to have compatibility with windows

**Comment by musiko** [comment]
1. Remove all Japanese comments
2. Move all initialization of data members into constructor function , i.e.

```
int no;
int layer;
int gridRes;
int prev_gridRes;

ofxBezierWarp(){
    no = 0;
    layer = 0;
    gridRes = 0;
    prev_gridRes = 0;
}
```

**Comment by TsubokuLab** [comment]
Thank you. I fixed this problem.
